"""add_tolerancia_setor

Revision ID: 91fbe6db1f17
Revises: ec4d5561cd97
Create Date: 2025-12-06 20:44:01.026246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91fbe6db1f17'
down_revision: Union[str, Sequence[str], None] = 'ec4d5561cd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setores', sa.Column('tolerancia', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_setores_id'), table_name='setores')
    op.drop_column('setores', 'tolerancia')
    op.alter_column('projetos', 'data_inicio',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('projetos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('perguntas', sa.Column('opcoes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('perguntas', 'eh_obrigatoria',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'opcoes', type_='foreignkey')
    op.drop_constraint(None, 'opcoes', type_='foreignkey')
    op.create_foreign_key(op.f('opcoes_pergunta_id_fkey'), 'opcoes', 'perguntas', ['pergunta_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('opcoes_proxima_pergunta_id_fkey'), 'opcoes', 'perguntas', ['proxima_pergunta_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_opcoes_id'), table_name='opcoes')
        # ### end Alembic commands ###
