"""add_tolerancia_setor

Revision ID: 91fbe6db1f17
Revises: ec4d5561cd97
Create Date: 2025-12-06 20:44:01.026246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '91fbe6db1f17'
down_revision: Union[str, Sequence[str], None] = 'ec4d5561cd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setores', sa.Column('tolerancia', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove somente a coluna criada por esta migration."""
    op.drop_column('setores', 'tolerancia')
